Subscription button
OpenNeuroOrg/openneuro pull request #1113
Opened 2019-05-03 05:37 UTC by DaNish808

![Screen Shot 2019-05-02 at 22 33 27](https://user-images.githubusercontent.com/28666458/57121173-96f1e500-6d2a-11e9-83d8-88e7358994da.png)

Newsletter model created with fields email & created.
Backend email validation.

2019-05-03 17:05 UTC, nellh requested changes
This looks good but could use some tests for the expected function behavior around the states and mutation.

It needs a few linting fixes as well.

2019-05-03 17:05 UTC, nellh commented on packages/openneuro-server/models/newsletter.js
> +  email: 'string',
I'd make this field required and unique.

2019-05-07 22:38 UTC, DaNish808 commented
Refactors done, tests added, and linting errors resolved. @nellh

2019-05-08 19:28 UTC, nellh approved these changes

2019-05-08 19:29 UTC, merged