1331 responsive homepage
OpenNeuroOrg/openneuro pull request #1353
Opened 2019-10-23 17:39 UTC by MatthewZito

These changes make the front page responsive -> the containers are now flex and the gray offset on the right side of the page is now gone. I've also added a media query that draws a small inset border between the green "recent activity" cards; via mobile, they now appear as two discrete entities and the typographic hierarchy of the headers remains apparent (whereas before, this emphasis was lost on mobile).

2019-10-23 21:52 UTC, david-nishi approved these changes
Tested on Galaxy S6 Chrome: looks great!

2019-10-29 22:31 UTC, nellh requested changes
This decenters the viewport for desktop in Chrome and Firefox:

![Screenshot from 2019-10-29 15-19-17](https://user-images.githubusercontent.com/11369795/67813743-8a431500-fa5f-11e9-8946-a8c765ec05f6.png)

On mobile, things look good in Chrome and Firefox. I think the condensed top datasets view is great. In Safari, the page horizontally scrolls but does look better on initial load.

2019-10-30 20:15 UTC, MatthewZito commented
> This decenters the viewport for desktop in Chrome and Firefox:
> 
> ![Screenshot from 2019-10-29 15-19-17](https://user-images.githubusercontent.com/11369795/67813743-8a431500-fa5f-11e9-8946-a8c765ec05f6.png)
> 
> On mobile, things look good in Chrome and Firefox. I think the condensed top datasets view is great. In Safari, the page horizontally scrolls but does look better on initial load.

Fixed! Thanks

2019-11-04 20:30 UTC, nellh approved these changes

2019-11-04 20:34 UTC, merged