responsive dataset title and faq page
OpenNeuroOrg/openneuro pull request #1354
Opened 2019-10-23 18:53 UTC by MatthewZito

These changes address issues:

 - [[ON-1333]](https://github.com/OpenNeuroOrg/openneuro/issues/1333)
 - [[ON-1334]](https://github.com/OpenNeuroOrg/openneuro/issues/1334)
 - [[ON-1340] ](https://github.com/OpenNeuroOrg/openneuro/issues/1340)

Note: The sort, dataset summary, and filter (on private dashboards) issues are being postponed for further review of certain design decisions that need to be made. For now, the preceding three issues are addressed in this PR.

2019-10-23 21:18 UTC, david-nishi approved these changes

2019-10-23 21:18 UTC, david-nishi commented on packages/openneuro-app/src/sass/crn_app/_dashboard.datasets.scss
> +                color: #333;
i think this will get inherited from .minimal-summary

2019-10-29 23:07 UTC, nellh requested changes
The FAQ change works great.

I'm running into some problems with the dashboard changes. Screenshots from Firefox but it seems about the same in Chrome.

Sometimes the summary data is not visible at all:
![Screenshot from 2019-10-29 15-51-36](https://user-images.githubusercontent.com/11369795/67815422-1eaf7680-fa64-11e9-92b1-8326a2c2f4f9.png)

It is also breaking the alignment of the design and text is clipped at the bottom (see the G characters):
![Screenshot from 2019-10-29 15-46-52-2](https://user-images.githubusercontent.com/11369795/67815668-cfb61100-fa64-11e9-9f2f-1f6447c82d1f.png)

Looks like this introduces some variable height in some cases to these rows, which will result in rendering issues with the virtual scroll implementation.

2019-10-29 23:57 UTC, MatthewZito commented
> Looks like this introduces some variable height in some cases to these rows, which will result in rendering issues with the virtual scroll implementation.

I should've marked this WIP. After meeting with Eric, there are going to be some more changes on the dashboard (e.g. removing most of the summary data tabs on mobile, removing the 'public dashboard' tab at the top left, et al); I'll make sure the issues you cited are fixed when I address them. Thanks for bringing that to my attention

2019-10-30 16:21 UTC, closed without merging