[WIP] 1339 responsive readme
OpenNeuroOrg/openneuro pull request #1363
Opened 2019-10-24 22:42 UTC by MatthewZito

Although addressing a small issue (for now), the solution herein should be immensely helpful in the continued development of OpenNeuro as a more responsive platform. I've written a custom hook - `useMedia` - which empowers the utility of media queries inside of component logic, effectively making conditional rendering for mobile accessible anywhere in the codebase, and without first having to instantiate state + lifecycle methods to determine innerWidth. It's built such that it can easily be modified to accept an array of breakpoints so as to handle multiple media queries in a single component (if ever needed). Other props could probably be passed in, too. 

I've also included an 'accordion', or 'collapsible', styled wrapper/component. This component will probably see heavy usage on mobile; so, too, will it probably see heavy refactoring. I certainly don't think the unicode arrows or text fields are as great as they could be, and I am thus open to recommendations. I think the final design will be easier ascertained when the dataset page redesign (in totality) is worked on. 

WIP not yet in need of review

2019-10-30 17:01 UTC, david-nishi requested changes

2019-10-30 17:01 UTC, david-nishi commented on packages/openneuro-app/src/scripts/datalad/dataset/dataset-description.jsx
> +  isMobile,
This is missing from propTypes; breaking linter.

2019-10-30 19:57 UTC, MatthewZito commented on packages/openneuro-app/src/scripts/mobile/collapsible-wrapper.jsx
> +      {!isOpen && (
> I think we should move this ternary internal to title square bracket accessors.
Excellent point. Doneskies.

2019-10-30 22:10 UTC, MatthewZito commented on packages/openneuro-app/src/scripts/mobile/collapsible-wrapper.jsx
> +  font-size: 14px;
Okay. Accidentally left that 14px in there when copying over link styles. I've just removed it; the show more/less text is now the same size as other text using that same font (seems to be the proverbial 'do something' typefont across OpenNeuro). 

Side note: I realized that the collapsible needs to be omitted when README content is null, lest we get an arbitrary gap and confusing 'show more/less' button with no text. To that end, I added a content (props) check to the condition in `dataset-readme`. Just a heads up.

2019-11-04 18:19 UTC, MatthewZito commented
Note: I realized that the collapsible was being rendered even when there was no README content. The problem this caused was the collapsible still afforded whitespace and thus would collapse to say "show less" and while ostensibly fully expanded, say "show more". I added [a condition that checks for content in the README before rendering the collapsible wrapper. ](https://github.com/OpenNeuroOrg/openneuro/pull/1363/commits/bad7ca53babc12071db9369313c180bc819209db)

2019-11-13 17:44 UTC, david-nishi approved these changes
Looks good!

2019-11-18 22:16 UTC, merged