mobile-only dashboard styling
OpenNeuroOrg/openneuro pull request #1373
Opened 2019-10-30 22:43 UTC by MatthewZito

[1333](https://github.com/OpenNeuroOrg/openneuro/issues/1333)
[1334](https://github.com/OpenNeuroOrg/openneuro/issues/1334)

This should fix issues 1333, 1334 on the mobile view, without affecting desktop (as was the case in prior attempt). I've tested the metrics container stylings and all appears fine on my local instance, but there seem to be some possible edge cases on the actual prod version of the site. I applied the styles to the prod version, but this was done via dev tools. Still, I think it should work.

Notes: The dashboard title tab (i.e. the tab beneath the nav eg 'public dashboard'), uploader name, upload date, and status icons have been removed per the conclusions of the most recent discussion about the mobile view of the dashboard.

2019-11-06 21:04 UTC, MatthewZito commented
Note: [this commit](https://github.com/OpenNeuroOrg/openneuro/blob/528b6cc0aec3830f89a71aa519e637b4fad26e3b/packages/openneuro-app/src/scripts/datalad/dataset/__tests__/__snapshots__/comments.spec.jsx.snap) uses the diction "_almost_ NaN years ago" for the shapshot whereas the format is "_about_ NaN years ago". It's causing a test failure, so I changed it in the most recent commit on this PR.

2019-11-07 18:42 UTC, david-nishi requested changes
Looks so much better! Vertically stacking the metadata and metrics fits really well and everything that should be display is visible now. 

There are a couple of small fixes that could be made to the panel styles right around the high range of the media queries, including title text with cut off descenders and a slight overlap of the metadata and metrics containers.

<img width="583" alt="Screen Shot 2019-11-07 at 10 34 32" src="https://user-images.githubusercontent.com/28666458/68417691-bb9c9e80-014b-11ea-8c98-a159a937aee8.png">

2019-11-07 18:42 UTC, david-nishi commented on packages/openneuro-app/src/sass/crn_app/_dashboard.datasets.scss
> +        display: none;
This could use an indent

2019-11-07 18:42 UTC, david-nishi commented on packages/openneuro-app/src/sass/crn_app/_dashboard.datasets.scss
>              }
Media-queried .metric-container and .status-container styles could be bundled together since they share the same type, feature, and level.

2019-11-13 17:54 UTC, MatthewZito commented
@david-nishi I'm going to remove the 'available' in the tasks/modalities before you review this.

2019-11-13 17:57 UTC, david-nishi commented
Was just about to comment on that. After that's done this is good to go.

2019-11-14 17:19 UTC, david-nishi approved these changes

2019-11-14 17:19 UTC, david-nishi commented on packages/openneuro-app/src/scripts/datalad/fragments/dataset-summary.jsx
> +          <b className="desktop">Available</b> {type} : {items.join(', ')}
What do you think about making this class "desktop-only"?

2019-11-18 22:17 UTC, merged