Mozilla support and css updates
OpenNeuroOrg/openneuro pull request #199
Opened 2017-11-07 19:24 UTC by Xesme

This branch adds updates to styling and enables Mozilla Firefox support.  Issue #81

2017-11-07 20:00 UTC, nellh requested changes
Have a few screenshots of other issues I'll add to the PR comments.

2017-11-07 20:00 UTC, nellh commented on app/src/scripts/common/partials/happybrowser.jsx
> +      bowser.check(
This check should not include Firefox, it is a fallback for Googlebot (Chrome 41 only).

2017-11-07 20:00 UTC, nellh commented on app/src/scripts/common/partials/happybrowser.jsx
> +                  Please consider using Chrome or Firefox, V49.0 or higher, as
This should specify Chrome 49 and Firefox 50.

2017-11-07 20:00 UTC, nellh commented on app/src/sass/crn_app/_elements-wrappers.scss
> +    font-weight: 600;
This seems to change the font-weight for all of the analysis views. Is that intentional?

2017-11-07 20:05 UTC, nellh commented
Datasets dashboard filters wrap in Firefox.

![datasets-wrap](https://user-images.githubusercontent.com/11369795/32514947-5b1db666-c3b3-11e7-8559-77815087c2f9.png)

This "draft dataset has been deleted" message is visible in Firefox but not Chrome.

![draft-dataset](https://user-images.githubusercontent.com/11369795/32514986-750415d4-c3b3-11e7-8d8e-06f732fe8780.png)

Panels in the analysis components have some extra space.

![job-status-spacing](https://user-images.githubusercontent.com/11369795/32515021-9266c4b4-c3b3-11e7-8810-6a6ba268f0a7.png)

In both Firefox and Chrome, the upload dataset tabs are no longer aligned.

![tabs](https://user-images.githubusercontent.com/11369795/32515122-e904f520-c3b3-11e7-9b86-efac0c7a600b.png)

2017-11-07 20:08 UTC, nellh commented
I've also noticed two upload bugs with Firefox.

* The check for a dataset with the same name does not work, Firefox will let you upload a dataset with the same name as one uploaded by Chrome and silently fail out of the upload process.
* Somehow "%3A" got prepended to dataset_descripton.json's filename on a successful upload that had been resumed. "%3Adataset_description.json".

2017-11-07 22:22 UTC, Xesme commented
@nellh I think we may be having some os/linux styling issues. 

I can see 'This "draft dataset has been deleted" message is visible in Firefox but not Chrome.' within both FF and Chrome.
<img width="309" alt="screen shot 2017-11-07 at 2 17 33 pm" src="https://user-images.githubusercontent.com/24839005/32520990-c65c5cb2-c3c6-11e7-8cc6-8c512d2ff5f2.png">

Also, my datasets dashboard filters do not wrap in FF.

![screen shot 2017-11-07 at 2 17 49 pm](https://user-images.githubusercontent.com/24839005/32521059-f9388dd6-c3c6-11e7-82c4-bec207101c4f.png)
![screen shot 2017-11-07 at 2 18 05 pm](https://user-images.githubusercontent.com/24839005/32521063-fa8aa1ce-c3c6-11e7-8ba5-772c96df43cd.png)

2017-11-08 18:11 UTC, nellh commented
@Xesme Is there a good reason to not remove the width on `.filters-sort-wrap .filters` - it seems this fixes the Linux wrapping issue with the dataset filters.

2017-11-08 18:13 UTC, Xesme commented
@nellh unfortunately, it was added as a fix to wrapping filters on OS. I will try to find another work around.

2017-11-08 18:22 UTC, Xesme commented
@nell originally I had added it to prevent wrapping on OS Mozilla, I just tested it by taking it it out, seems like it's not causing an issue anymore. I think it may be related to the same issue within the upload modal, which was an inherited style that has been changed. I will push a fix right now.

2017-11-08 18:22 UTC, Xesme commented
@nell originally I had added it to prevent wrapping on OS Mozilla, I just tested it by taking it it out, seems like it's not causing an issue anymore. I think it may be related to the same issue within the upload modal, which was an inherited style that has been changed. I will push a fix right now.

2017-11-08 18:22 UTC, Xesme commented
@nell originally I had added it to prevent wrapping on OS Mozilla, I just tested it by taking it it out, seems like it's not causing an issue anymore. I think it may be related to the same issue within the upload modal, which was an inherited style that has been changed. I will push a fix right now.

2017-11-09 19:24 UTC, nellh approved these changes

2017-11-09 19:30 UTC, merged