created tooltip
OpenNeuroOrg/openneuro pull request #2096
Opened 2021-05-01 03:16 UTC by thinknoack

2021-05-03 08:17 UTC, tranttommy requested changes

2021-05-03 08:17 UTC, tranttommy commented on packages/openneuro-components/src/Tooltip/Tooltip.tsx
> +  const myRef = React.createRef<HTMLSpanElement>()
You should use the `useRef` hook instead for this

2021-05-03 08:17 UTC, tranttommy commented on packages/openneuro-components/src/Tooltip/Tooltip.tsx
> +  ...props
What might the `...props` be used for?

2021-05-03 08:17 UTC, tranttommy commented on packages/openneuro-components/src/Tooltip/Tooltip.tsx
> +  children,
Need to include children in the `interface`. The type for `children` would be `React.ReactNode`

2021-05-03 08:17 UTC, tranttommy commented on packages/openneuro-components/src/Tooltip/Tooltip.stories.tsx
> +Up.parameters = {
What does this `parameters` property do?

2021-05-05 23:03 UTC, tranttommy approved these changes
Tooltips look good, but we may want to merge in the Radio buttons branch before this. I would suggest not branching off another component branch next time to make things easier to review and merge.

2021-05-06 16:21 UTC, thinknoack reviewed
> Tooltips look good, but we may want to merge in the Radio buttons branch before this. I would suggest not branching off another component branch next time to make things easier to review and merge.

yep, thats how my other branches are. There was a reason I branched off of radio but I am not remembering why at the moment.

2021-05-06 16:22 UTC, merged