Two handle range
OpenNeuroOrg/openneuro pull request #2107
Opened 2021-05-06 16:22 UTC by thinknoack

2021-05-06 16:31 UTC, thinknoack commented
[Gitlab issue 125 ](https://gitlab.com/squishymedia/nimh/openneuropet/-/issues/125)

2021-05-13 23:59 UTC, tranttommy requested changes

2021-05-13 23:59 UTC, tranttommy commented on packages/openneuro-components/src/range/TwoHandleRange.tsx
> +    console.log(value)
remove console.log

2021-05-17 06:09 UTC, tranttommy requested changes

2021-05-17 06:09 UTC, tranttommy commented on packages/openneuro-components/src/range/TwoHandleRange.tsx
> +const Range = createSliderWithTooltip(Slider.Range)
This can probably be simplified to `const Range = Slider.createSliderWithTooltip(Slider.Range)`

2021-05-18 03:39 UTC, thinknoack commented
@tranttommy  any suggestions on the type error (for pushable) in the failed checks above?

2021-05-18 18:46 UTC, tranttommy approved these changes
Looks good!

2021-05-20 19:44 UTC, merged