refactor(components): Drop rc-slider and use our own two handle range
OpenNeuroOrg/openneuro pull request #2176
Opened 2021-06-23 22:06 UTC by nellh

This drops rc-slider and fixes #2175 

Based this on a [simple example](https://codesandbox.io/s/b9l0g) and added back in some of the features we were using from rc-slider. The one thing missing is the step or range indicators, do we need those? I didn't touch the CSS at all, so that is WIP.

2021-06-23 22:36 UTC, thinknoack requested changes

2021-06-23 22:36 UTC, thinknoack commented on packages/openneuro-components/src/range/TwoHandleRange.scss
> +}
```suggestion

.formRange-inner {
  max-width: 80%;
  margin: 0 auto;

  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  min-width: 270px;
  position: relative;
  padding: 0 0 30px;
  }
```

2021-06-23 22:36 UTC, thinknoack commented on packages/openneuro-components/src/range/TwoHandleRange.tsx
> +    <div className="container">
```suggestion
    <div className="formRange-inner">
```

2021-06-25 21:09 UTC, nellh commented
Merging this but it may still need colors fixed.

2021-06-25 21:10 UTC, merged