adding feedback form
OpenNeuroOrg/openneuro pull request #2267
Opened 2021-07-26 22:06 UTC by thinknoack

initial functionality for feedback via google forms

2021-07-28 05:02 UTC, nellh requested changes

2021-07-28 22:58 UTC, thinknoack commented
added some default styles and interactions. ready for re-review

2021-07-28 23:05 UTC, nellh approved these changes
Couple suggestions but otherwise looks good.

2021-07-28 23:05 UTC, nellh commented on packages/openneuro-app/src/scripts/refactor_2021/redesign-form.jsx
> +    console.log(response)
```suggestion
    fetch(url, { method: 'POST' })
```
Fetch returns a promise so this never throws.

2021-07-28 23:05 UTC, nellh commented on packages/openneuro-app/src/scripts/refactor_2021/redesign-form.jsx
> +    console.log(this.state.entryFields)
```suggestion
```

2021-07-28 23:09 UTC, thinknoack commented
@nell committed suggestions and tested. all is working - i'll leave this here for Kate to review.  Ty

2021-08-06 20:41 UTC, ckrountree commented
Couple of comments:

1. The Feedback button may need a stronger call-to-action color.  I like the cleanliness and unobtrusiveness but it may also get lost.  Fine line. I leave this decision to you.
2. For the drop-down, I think that "OK" and "Soso" are redundant.  I'd also spell out "Okay". Trying to avoid a "bad" connotation, I might change the wording to "Poor" - gets the point across without being as strong.
![Screen Shot 2021-08-06 at 1 00 59 PM](https://user-images.githubusercontent.com/27043528/128565367-1474926e-b544-4ffa-a766-23893874b008.png)

3. I would make it clearer what the two places you are asking about are:
![first found modality portal](https://user-images.githubusercontent.com/27043528/128564581-5eb101b6-31bf-4eb1-9e4c-45ea9a27c722.png)

4. I would suggest adding an additional question to assess overall experience (not just Search).  Something with the tone such as, "How intuitive did you find the redesign functionality?" and then use the same _Great, Good, Okay, Poor_ options used in the Search drop-down. Maybe provide a follow-up if rating is not _Great_: "If not great, what was not intuitive?"

2021-08-06 20:44 UTC, ckrountree commented
Copied from PR 2271: 
> 2\. For the drop-down, I think that "OK" and "Soso" are redundant.  I'd also spell out "Okay". Trying to avoid a "bad" connotation, I might change the wording to "Poor" - gets the point across without being as strong.


this is one eric wanted and he definitely didn't want good/bad. More like "The redesign is great, I find it very easy to use" and "I think the redesign is good overall".

I just need help with statements like that. They dont have to be good or bad.

2021-08-06 20:51 UTC, thinknoack commented
> 4\. I would suggest adding an additional question to assess overall experience (not just Search).  Something with the tone such as, "How intuitive did you find the redesign functionality?" and then use the same _Great, Good, Okay, Poor_ options used in the Search drop-down. Maybe provide a follow-up if rating is not _Great_: "If not great, what was not intuitive?"

I am a little confused about this. The dropdown is about the redesign. Do you want to add another that is for Search?

2021-08-07 00:12 UTC, ckrountree commented
> > 4. I would suggest adding an additional question to assess overall experience (not just Search).  Something with the tone such as, "How intuitive did you find the redesign functionality?" and then use the same _Great, Good, Okay, Poor_ options used in the Search drop-down. Maybe provide a follow-up if rating is not _Great_: "If not great, what was not intuitive?"
> 
> I am a little confused by this. The dropdown is about the redesign. Do you want to add another that is for Search?

Not necessarily.  You have the question "When searching for a dataset were you able to find relevant results?" in the form.  If we're asking about the ease of searching, I'd also like to know how intuitive the UI is for users.  That said, that could be accomplished if you decide to go with a rating drop-down more like:

**Which of the following best describes your experience with the redesign today?**
- Exciting and easy to navigate
- Visually pleasing, not quite as intuitive
- Couldn’t achieve my goal
- 
 Then follow up with a Q if the user selects _Visually pleasing, not quite as intuitive_ or _Couldn’t achieve my goal_ (what was not intuitive, what was your goal)

2021-08-08 22:58 UTC, thinknoack commented
> > > 1. I would suggest adding an additional question to assess overall experience (not just Search).  Something with the tone such as, "How intuitive did you find the redesign functionality?" and then use the same _Great, Good, Okay, Poor_ options used in the Search drop-down. Maybe provide a follow-up if rating is not _Great_: "If not great, what was not intuitive?"
> > 
> > 
> > I am a little confused by this. The dropdown is about the redesign. Do you want to add another that is for Search?
> 
> Not necessarily. You have the question "When searching for a dataset were you able to find relevant results?" in the form. If we're asking about the ease of searching, I'd also like to know how intuitive the UI is for users. That said, that could be accomplished if you decide to go with a rating drop-down more like:
> 
> **Which of the following best describes your experience with the redesign today?**
> 
> * Exciting and easy to navigate
> * Visually pleasing, not quite as intuitive
> * Couldn’t achieve my goal
> 
> Then follow up with a Q if the user selects _Visually pleasing, not quite as intuitive_ or _Couldn’t achieve my goal_ (what was not intuitive, what was your goal)

I believe this has been accomplished with the changes I added to the form. Let's discuss when you have had a chance to review.

2021-08-09 19:35 UTC, ckrountree commented
Do we want to add "_Good overall experience_"?  It may seem redundant with the first option. I'll leave that to your discretion:
![Screen Shot 2021-08-09 at 12 30 28 PM](https://user-images.githubusercontent.com/27043528/128763313-8e7c21db-1631-4a93-a075-102108574fba.png)

I might be more explicit here: "_If the new design did not feel as intuitive or if you were unable to achieve your goal(s), please explain further._"
![Screen Shot 2021-08-09 at 12 30 40 PM](https://user-images.githubusercontent.com/27043528/128763518-12497447-36d6-47ec-b246-84b27b2486e6.png)

Misspelling (`were`):

![Screen Shot 2021-08-09 at 12 32 55 PM](https://user-images.githubusercontent.com/27043528/128763627-ce40a49b-5607-4115-9b6f-fe62dacfaad3.png)

2021-08-09 21:32 UTC, ckrountree approved these changes

2021-08-09 22:04 UTC, merged