linking modalities on datasets to portals
OpenNeuroOrg/openneuro pull request #2302
Opened 2021-08-20 20:18 UTC by thinknoack

2021-08-20 20:29 UTC, nellh requested changes

2021-08-20 20:29 UTC, nellh commented on packages/openneuro-components/src/dataset/ModalitiesMetaDataBlock.tsx
> +    console.log(arr)
Extra console.log
```suggestion
```

2021-08-20 21:59 UTC, david-nishi requested changes

2021-08-20 21:59 UTC, david-nishi commented on packages/openneuro-components/src/dataset/ModalitiesMetaDataBlock.tsx
> +  className,
Since this component is specific to a single feature, i think we can just hardcode these props.

2021-08-20 21:59 UTC, david-nishi commented on packages/openneuro-components/src/dataset/ModalitiesMetaDataBlock.tsx
> +      )}
Instead of going through markdown-to-jsx, we could just use jsx. This would also let us use <Link/> from react-router-dom instead of anchor tags.

2021-08-24 23:11 UTC, david-nishi approved these changes

2021-08-25 19:15 UTC, merged