Edit field
OpenNeuroOrg/openneuro pull request #2315
Opened 2021-08-25 23:37 UTC by thinknoack

2021-08-27 20:15 UTC, thinknoack commented
un-styled edit dataset functionality for lists and blocks

2021-08-31 18:00 UTC, david-nishi requested changes

2021-08-31 18:00 UTC, david-nishi commented on packages/openneuro-components/src/dataset/MetaDataListBlock.tsx
> +      <>{fieldContent}</>
```suggestion
      {fieldContent}
```

2021-09-06 21:24 UTC, thinknoack commented
@OpenNeuroOrg/squishymedia ready for rere

2021-09-07 17:20 UTC, david-nishi approved these changes

2021-09-07 18:29 UTC, merged