Follow bookmark login
OpenNeuroOrg/openneuro pull request #2356
Opened 2021-09-24 18:40 UTC by david-nishi

## Major changes
- Add redirect option to client login.
- When a user clicks a dataset's follow or bookmark button when not logged in, the login modal is displayed. Once logged in, the user is taken back to the dataset page they were on and the button they clicked is triggered for them.

2021-09-24 18:48 UTC, thinknoack commented
Looks good. One thing I saw

If a user has already favorited the dataset, when logged out it redirects them back to the dataset and "unfollows".

2021-09-24 22:25 UTC, thinknoack approved these changes

2021-09-28 18:16 UTC, nellh requested changes

2021-09-28 18:16 UTC, nellh commented on packages/openneuro-server/src/libs/authentication/jwt.js
> +    ? atob(req.query.state)
You can avoid adding atob (unmaintained package and obsolete in Node 16) like this:
```suggestion
    ? Buffer.from(req.query.state, 'base64').toString()
```

2021-09-28 19:31 UTC, nellh approved these changes

2021-09-28 19:31 UTC, merged