update resolver to query user by orcid or id
OpenNeuroOrg/openneuro pull request #3258
Opened 2024-12-17 23:56 UTC by thinknoack

I am still having a lot of yarn issues so running yarn test produces errors related to the various modules with checksum errors. 

This is my first stab at updating the resolver so a user can be queried by orcid. LMK

2024-12-19 22:23 UTC, thinknoack commented
@nellh - I think I have this as we discussed.

2025-01-07 20:35 UTC, nellh requested changes
Most of this looks good. The precommit hook didn't get run so the formatting is wrong in some spots. One fix needed for the functionality but it would also be good to fix the formatting.

2025-01-07 20:35 UTC, nellh commented on packages/openneuro-server/src/graphql/resolvers/user.ts
> +    return User.findOne({ "orchid": id }).exec()
```suggestion
    return User.findOne({ "orcid": id }).exec()
```

2025-01-07 20:35 UTC, nellh commented on packages/openneuro-server/src/graphql/resolvers/user.ts
> +    return User.findOne({ "orchid": id }).exec()
One typo here but another limitation is there's two kinds of user records here:

```json
{
  "provider": "orcid",
  "providerId": "0000-0000..."
}
```

```json
{
  "provider": "google",
  "orcid": "0000-0000..."
}
```

This branch needs to find both of these. Once we've migrated Google users to ORCID logins, most users will fall into the first group that won't match here.

2025-01-07 21:53 UTC, thinknoack commented on packages/openneuro-server/src/graphql/resolvers/user.ts
> +    return User.findOne({ "orchid": id }).exec()
updated typo.

2025-01-07 22:01 UTC, thinknoack commented on packages/openneuro-server/src/graphql/resolvers/user.ts
> +    return User.findOne({ "orchid": id }).exec()
@nellh something like this?

export const user = (obj, { id, key }) => {
  function isValidOrcid(orcid: string): boolean {
    return /^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$/.test(orcid || "")
  }

  if (isValidOrcid(id)) {
    if (key === 'orcid') {
      return User.findOne({ "orcid": id }).exec(); // Search by orcid if key is 'orcid'
    } else {
      return User.findOne({ "providerId": id }).exec(); // Otherwise, search by providerId
    }
  } else {
    return User.findOne({ "id": id }).exec(); // Search by id if not a valid ORCID
  }
}

2025-01-07 22:10 UTC, nellh commented on packages/openneuro-server/src/graphql/resolvers/user.ts
> +    return User.findOne({ "orchid": id }).exec()
It should be a single query, you can use the `{$or: [{ "orcid": id }, {"providerId": id}]}` operator to check if the id is in either field. No need for a key argument.

2025-01-07 22:37 UTC, thinknoack commented on packages/openneuro-server/src/graphql/resolvers/user.ts
> +    return User.findOne({ "orchid": id }).exec()
ty - that was helpful. I have that added now

2025-01-08 19:33 UTC, nellh approved these changes

2025-01-08 19:34 UTC, merged