dataset modal routing and snapshot changelog
OpenNeuroOrg/openneuro pull request #437
Opened 2018-02-22 00:18 UTC by olgn

fixes #327, #424, and #425 

reason for combining these: when working on #327, it became apparent that the create snapshot modal should be broken into a separate view. 

however, there were modals (publish, jobs) that contained 'create new snapshot' buttons within them.  if a user navigated to the snapshot creation view from a modal, it would be very difficult to keep track of what modal it came from. 

the solution is to create routes for each modal, and utilize these modals to control navigation between snapshot creation, as well as control the activation / deactivation of modals.

changes to modals:
* toggling a modal from the dataset toolbar now links to a separate url, /dataset/datasetId?modal=modalname
* closing a modal links the user back to the /dataset/datasetId url

changes to new snapshot workflow:
* creating a new snapshot now involves specifying a version number (locked at next major version until we implement major, minor, and point versioning) 
* creating a new snapshot now involves specifying a changelog
* saving a snapshot will format changes and attach the new changes to the old changelog, along with version number and date
* the snapshot notification email now contains the updated changelog, to inform followers about updates
* user will not be able to see the 'create new snapshot' link from within publish / jobs modals unless the dataset has been modified

2018-02-23 18:38 UTC, nellh requested changes
The query string should be reserved for queries, a verb is better structured as '/datasets/ds000001/create-snapshot'. Hyphens are also preferred so that individual words are more clearly delineated in a URL (especially for search engines). These can also be implemented as actual Route components instead of parsing in componentWillReceiveProps.

Ran into one bug - deleting a snapshot suggests and lets you reuse version numbers.

We may want to hide the extra version parameters if it is not available with the SciTran backend. The disabled boxes are confusing.

2018-03-02 23:06 UTC, olgn commented
@nellh all three points of feedback have been addressed. 

* modals now use datseturl/modalname routing methods
* the modals themselves have been turned into components which are rendered within the dataset page

2018-03-08 17:32 UTC, nellh requested changes
A couple extra router dependencies but this looks pretty good now. yarn.lock might need to be fixed and merge conflicts need to be resolved.

2018-03-08 17:32 UTC, nellh commented on app/src/scripts/common/forms/warn-button.jsx
> +export default withRouter(WarnButton)
It doesn't look like this is needed.

2018-03-08 17:32 UTC, nellh commented on app/src/scripts/common/partials/file-tree.jsx
> +    let history = this.props.history
This probably isn't needed either.

2018-03-08 19:49 UTC, nellh approved these changes

2018-03-08 19:49 UTC, merged