Download count to dashboard
OpenNeuroOrg/openneuro pull request #505
Opened 2018-03-21 18:49 UTC by olgn

fixes #432 

* dataset usage statistics are now added to each dataset returned by the dashboard dataset store.
* dataset downloads are added to the metrics component in the dataset page
* dataset downloads are added to the public dataset dashboard
* dataset dashboard is filterable by download count

2018-03-21 20:59 UTC, nellh requested changes
This looks like it breaks the follow dataset dialogue and does not actually count downloads.

2018-03-21 20:59 UTC, nellh commented on app/src/scripts/common/partials/metric.jsx
> +        tip = 'This dataset has ' + value + ' download.'
"downloads"

2018-03-21 21:11 UTC, nellh commented
Clarifying the issue, drafts show a download count but downloads for a draft are not actually counted. The follow page does display as it should.

2018-03-22 18:20 UTC, olgn commented
@nellh those review points have been addressed

2018-03-22 18:22 UTC, nellh approved these changes

2018-03-22 18:22 UTC, merged