reply to comment via email
OpenNeuroOrg/openneuro pull request #508
Opened 2018-03-22 17:10 UTC by olgn

setup necessary for testing #434 

* implements the /crn/comments/reply/:commentId/:userId route, which will be used by mailgun when comment notification emails are replied to.
* creates a handler for this route
* creates jest tests for the handler

2018-03-22 17:48 UTC, nellh requested changes

2018-03-22 20:56 UTC, olgn commented on server/handlers/comments.js
> +  async reply(req, res, next) {
reply now checks the mongo.collections.crn.mailgunIdentifiers collection agains the request's In-Reply-To field when a request is made to this endpoint. the collection is populated with the messageId when the notification is successfully sent.

2018-03-22 20:56 UTC, olgn commented on server/handlers/comments.js
> +  async reply(req, res, next) {
unit tests for this check have been written, as well

2018-03-30 16:52 UTC, nellh approved these changes

2018-03-30 16:52 UTC, nellh commented
This looks good, merging it and we should test with real emails on dev.

2018-03-30 16:53 UTC, merged